In [1]:
#@advance
import ast, copy
import warnings
import numpy as np
import pandas as pd, random
import types, sys
import os

In [2]:
#@param
base_py_file_name = 'sample_a.py'
add_py_file_name = 'sample_b.py'

In [3]:
#@default
auto_sort = True

In [4]:
if base_py_file_name[-3:] != '.py':
    base_py_file_name = base_py_file_name +'.py'

In [5]:
if not os.path.isfile(base_py_file_name):
    with open(base_py_file_name, 'w') as f:
        pass

In [6]:
with open(base_py_file_name) as f:
    base_p = copy.deepcopy(ast.parse(f.read()))
with open(add_py_file_name) as f:
    add_p = copy.deepcopy(ast.parse(f.read()))

In [7]:
#@ignore
output_str = ''
indent_num = 0
for c in ast.dump(base_p):
    if c == '(':
        indent_num = indent_num + 1
        output_str = output_str + c
        output_str = output_str + '\n' + '  '*indent_num
    elif c == ')':
        indent_num = indent_num - 1
        output_str = output_str + c
    elif c == '[':
        indent_num = indent_num + 1
        output_str = output_str + c
        output_str = output_str + '\n' + '  '*indent_num
    elif c == ']':
        indent_num = indent_num - 1
        output_str = output_str + c
    elif c == ',':
        output_str = output_str + c + '\n' + '  '*indent_num
    elif c == ' ':
        pass
    else:
        output_str = output_str + c
print(output_str)

Module(
  body=[
    For(
      target=Name(
        id='nbtof_test_b',
        ctx=Store(
          )),
      iter=Call(
        func=Name(
          id='range',
          ctx=Load(
            )),
        args=[
          Constant(
            value=1),
          Constant(
            value=10)],
        keywords=[
          ]),
      body=[
        Assign(
          targets=[
            Name(
              id='nbtof_test_c',
              ctx=Store(
                ))],
          value=Constant(
            value=4)),
        For(
          target=Name(
            id='i',
            ctx=Store(
              )),
          iter=Call(
            func=Name(
              id='range',
              ctx=Load(
                )),
            args=[
              Constant(
                value=4),
              Constant(
                value=6)],
            keywords=[
              ]),
          body=[
            Assign(
              targets=[
                Name(
                  id='nbtof_test_d',
                  ctx=Store(
                    ))],
              value=Name(
                id='i',
                ctx=Load(
                  ))),
            Expr(
              value=Call(
                func=Name(
                  id='print',
                  ctx=Load(
                    )),
                args=[
                  Name(
                    id='nbtof_test_d',
                    ctx=Load(
                      )),
                  Name(
                    id='nbtof_test_c',
                    ctx=Load(
                      ))],
                keywords=[
                  ]))],
          orelse=[
            ])],
      orelse=[
        ]),
    For(
      target=Tuple(
        elts=[
          Name(
            id='i',
            ctx=Store(
              )),
          Name(
            id='j',
            ctx=Store(
              ))],
        ctx=Store(
          )),
      iter=Call(
        func=Name(
          id='enumerate',
          ctx=Load(
            )),
        args=[
          Call(
            func=Name(
              id='range',
              ctx=Load(
                )),
            args=[
              Constant(
                value=1),
              Constant(
                value=10)],
            keywords=[
              ])],
        keywords=[
          ]),
      body=[
        Assign(
          targets=[
            Name(
              id='nbtof_test_c',
              ctx=Store(
                ))],
          value=Constant(
            value=4))],
      orelse=[
        ]),
    Assign(
      targets=[
        Name(
          id='instnat_num',
          ctx=Store(
            ))],
      value=Constant(
        value=1)),
    While(
      test=Constant(
        value=True),
      body=[
        If(
          test=Compare(
            left=Name(
              id='instnat_num',
              ctx=Load(
                )),
            ops=[
              Gt(
                )],
            comparators=[
              Constant(
                value=5)]),
          body=[
            Assign(
              targets=[
                Name(
                  id='kk',
                  ctx=Store(
                    ))],
              value=Constant(
                value=3)),
            Break(
              )],
          orelse=[
            ]),
        Assign(
          targets=[
            Name(
              id='instnat_num',
              ctx=Store(
                ))],
          value=BinOp(
            left=Name(
              id='instnat_num',
              ctx=Load(
                )),
            op=Add(
              ),
            right=Constant(
              value=1)))],
      orelse=[
        ]),
    FunctionDef(
      name='concat_dum',
      args=arguments(
        posonlyargs=[
          ],
        args=[
          ],
        kwonlyargs=[
          ],
        kw_defaults=[
          ],
        defaults=[
          ]),
      body=[
        Return(
          value=Constant(
            value=None))],
      decorator_list=[
        ]),
    Import(
      names=[
        alias(
          name='matplotlib.pyplot',
          asname='plt')]),
    Import(
      names=[
        alias(
          name='numpy',
          asname='np'),
        alias(
          name='pandas',
          asname='pd'),
        alias(
          name='random')]),
    ImportFrom(
      module='matplotlib',
      names=[
        alias(
          name='pyplot',
          asname='plt')],
      level=0),
    ImportFrom(
      module='scipy.optimize',
      names=[
        alias(
          name='curve_fit')],
      level=0),
    ImportFrom(
      module='sklearn.gaussian_process.kernels',
      names=[
        alias(
          name='ConstantKernel'),
        alias(
          name='RBF'),
        alias(
          name='WhiteKernel')],
      level=0),
    Assign(
      targets=[
        Tuple(
          elts=[
            Name(
              id='nbtof_test_a',
              ctx=Store(
                )),
            Name(
              id='nbtof_test_b',
              ctx=Store(
                ))],
          ctx=Store(
            ))],
      value=Tuple(
        elts=[
          Constant(
            value=1),
          Constant(
            value=2)],
        ctx=Load(
          ))),
    Assign(
      targets=[
        Tuple(
          elts=[
            Name(
              id='nbtof_test_c',
              ctx=Store(
                )),
            Name(
              id='nbtof_test_d',
              ctx=Store(
                ))],
          ctx=Store(
            ))],
      value=Tuple(
        elts=[
          Constant(
            value=3),
          Constant(
            value=4)],
        ctx=Load(
          ))),
    FunctionDef(
      name='sample_a',
      args=arguments(
        posonlyargs=[
          ],
        args=[
          arg(
            arg='x'),
          arg(
            arg='y')],
        vararg=arg(
          arg='params'),
        kwonlyargs=[
          arg(
            arg='deg_for_fit')],
        kw_defaults=[
          Constant(
            value=4)],
        kwarg=arg(
          arg='kwargs'),
        defaults=[
          ]),
      body=[
        Expr(
          value=Constant(
            value='\nfdhjafsl\n')),
        FunctionDef(
          name='fit_func',
          args=arguments(
            posonlyargs=[
              ],
            args=[
              arg(
                arg='get_x')],
            vararg=arg(
              arg='params'),
            kwonlyargs=[
              ],
            kw_defaults=[
              ],
            defaults=[
              ]),
          body=[
            Assign(
              targets=[
                Name(
                  id='return_y',
                  ctx=Store(
                    ))],
              value=Call(
                func=Attribute(
                  value=Name(
                    id='np',
                    ctx=Load(
                      )),
                  attr='zeros_like',
                  ctx=Load(
                    )),
                args=[
                  Name(
                    id='get_x',
                    ctx=Load(
                      ))],
                keywords=[
                  ])),
            For(
              target=Tuple(
                elts=[
                  Name(
                    id='i',
                    ctx=Store(
                      )),
                  Name(
                    id='param',
                    ctx=Store(
                      ))],
                ctx=Store(
                  )),
              iter=Call(
                func=Name(
                  id='enumerate',
                  ctx=Load(
                    )),
                args=[
                  Name(
                    id='params',
                    ctx=Load(
                      ))],
                keywords=[
                  ]),
              body=[
                Assign(
                  targets=[
                    Name(
                      id='return_y',
                      ctx=Store(
                        ))],
                  value=BinOp(
                    left=Name(
                      id='return_y',
                      ctx=Load(
                        )),
                    op=Add(
                      ),
                    right=Call(
                      func=Attribute(
                        value=Name(
                          id='np',
                          ctx=Load(
                            )),
                        attr='array',
                        ctx=Load(
                          )),
                      args=[
                        BinOp(
                          left=Name(
                            id='param',
                            ctx=Load(
                              )),
                          op=Mult(
                            ),
                          right=BinOp(
                            left=Name(
                              id='get_x',
                              ctx=Load(
                                )),
                            op=Pow(
                              ),
                            right=Name(
                              id='i',
                              ctx=Load(
                                ))))],
                      keywords=[
                        ])))],
              orelse=[
                ]),
            Return(
              value=Name(
                id='return_y',
                ctx=Load(
                  )))],
          decorator_list=[
            ]),
        Assign(
          targets=[
            Tuple(
              elts=[
                Name(
                  id='popt',
                  ctx=Store(
                    )),
                Name(
                  id='pcov',
                  ctx=Store(
                    ))],
              ctx=Store(
                ))],
          value=Call(
            func=Name(
              id='curve_fit',
              ctx=Load(
                )),
            args=[
              Name(
                id='fit_func',
                ctx=Load(
                  )),
              Name(
                id='x',
                ctx=Load(
                  )),
              Name(
                id='y',
                ctx=Load(
                  ))],
            keywords=[
              keyword(
                arg='p0',
                value=Call(
                  func=Name(
                    id='list',
                    ctx=Load(
                      )),
                  args=[
                    Call(
                      func=Attribute(
                        value=Name(
                          id='np',
                          ctx=Load(
                            )),
                        attr='ones',
                        ctx=Load(
                          )),
                      args=[
                        BinOp(
                          left=Name(
                            id='deg_for_fit',
                            ctx=Load(
                              )),
                          op=Add(
                            ),
                          right=Constant(
                            value=1))],
                      keywords=[
                        ])],
                  keywords=[
                    ]))])),
        Assign(
          targets=[
            Name(
              id='check_y',
              ctx=Store(
                ))],
          value=Call(
            func=Name(
              id='fit_func',
              ctx=Load(
                )),
            args=[
              Name(
                id='x',
                ctx=Load(
                  )),
              Starred(
                value=Name(
                  id='popt',
                  ctx=Load(
                    )),
                ctx=Load(
                  ))],
            keywords=[
              ])),
        Return(
          value=Name(
            id='check_y',
            ctx=Load(
              )))],
      decorator_list=[
        ])],
  type_ignores=[
    ])

In [8]:
#@ignore
output_str = ''
indent_num = 0
for c in ast.dump(add_p):
    if c == '(':
        indent_num = indent_num + 1
        output_str = output_str + c
        output_str = output_str + '\n' + '  '*indent_num
    elif c == ')':
        indent_num = indent_num - 1
        output_str = output_str + c
    elif c == '[':
        indent_num = indent_num + 1
        output_str = output_str + c
        output_str = output_str + '\n' + '  '*indent_num
    elif c == ']':
        indent_num = indent_num - 1
        output_str = output_str + c
    elif c == ',':
        output_str = output_str + c + '\n' + '  '*indent_num
    elif c == ' ':
        pass
    else:
        output_str = output_str + c
print(output_str)

Module(
  body=[
    Import(
      names=[
        alias(
          name='numpy',
          asname='np'),
        alias(
          name='pandas',
          asname='pd'),
        alias(
          name='random')]),
    Import(
      names=[
        alias(
          name='cv2')]),
    Import(
      names=[
        alias(
          name='matplotlib.pyplot',
          asname='plt')]),
    ImportFrom(
      module='scipy.interpolate',
      names=[
        alias(
          name='interp1d')],
      level=0),
    Assign(
      targets=[
        Name(
          id='ast_sample_a',
          ctx=Store(
            ))],
      value=Constant(
        value=1)),
    FunctionDef(
      name='concat_dum',
      args=arguments(
        posonlyargs=[
          ],
        args=[
          ],
        kwonlyargs=[
          ],
        kw_defaults=[
          ],
        defaults=[
          ]),
      body=[
        Expr(
          value=Call(
            func=Name(
              id='print',
              ctx=Load(
                )),
            args=[
              Constant(
                value='sample_b')],
            keywords=[
              ])),
        Return(
          value=Constant(
            value=None))],
      decorator_list=[
        ]),
    FunctionDef(
      name='sample_b',
      args=arguments(
        posonlyargs=[
          ],
        args=[
          arg(
            arg='a'),
          arg(
            arg='b')],
        vararg=arg(
          arg='args'),
        kwonlyargs=[
          ],
        kw_defaults=[
          ],
        defaults=[
          ]),
      body=[
        Assign(
          targets=[
            Name(
              id='numpy',
              ctx=Store(
                ))],
          value=Constant(
            value=1)),
        Assign(
          targets=[
            Name(
              id='return_num',
              ctx=Store(
                ))],
          value=Constant(
            value=0)),
        For(
          target=Name(
            id='arg',
            ctx=Store(
              )),
          iter=Name(
            id='args',
            ctx=Load(
              )),
          body=[
            Assign(
              targets=[
                Name(
                  id='return_num',
                  ctx=Store(
                    ))],
              value=BinOp(
                left=Name(
                  id='return_num',
                  ctx=Load(
                    )),
                op=Add(
                  ),
                right=Name(
                  id='arg',
                  ctx=Load(
                    ))))],
          orelse=[
            ]),
        Assign(
          targets=[
            Name(
              id='return_num',
              ctx=Store(
                ))],
          value=BinOp(
            left=BinOp(
              left=Name(
                id='return_num',
                ctx=Load(
                  )),
              op=Add(
                ),
              right=Name(
                id='a',
                ctx=Load(
                  ))),
            op=Add(
              ),
            right=Name(
              id='b',
              ctx=Load(
                )))),
        Return(
          value=Name(
            id='return_num',
            ctx=Load(
              )))],
      decorator_list=[
        ])],
  type_ignores=[
    ])

In [9]:
#@advance
def body_dig(node, i = -1):
    return_name_table = []
    for j, node_u in enumerate(node.body):
        if type(node_u) == ast.Import:
            for name in node_u.names:
                if name.asname is not None:
                    return_name_table.append([name.asname, j * (i<0) + i * (i>=0), type(node_u), None, name.name, name.asname])
                else:
                    return_name_table.append([name.name, j * (i<0) + i * (i>=0), type(node_u), None, name.name, name.asname])
        elif type(node_u) == ast.ImportFrom:
            for name in node_u.names:
                if name.asname is not None:
                    return_name_table.append([name.asname, j * (i<0) + i * (i>=0), type(node_u), node_u.module, name.name, name.asname])
                else:
                    return_name_table.append([name.name, j * (i<0) + i * (i>=0), type(node_u), node_u.module, name.name, name.asname])
        elif type(node_u) == ast.Assign:
            if type(node_u.targets[0]) == ast.Tuple:
                for elt in node_u.targets[0].elts:
                    #return_name_table.append(elt.id)
                    return_name_table.append([elt.id, j * (i<0) + i * (i>=0), type(node_u), None, None, None])
            elif type(node_u.targets[0]) == ast.Name:
                return_name_table.append([node_u.targets[0].id, j * (i<0) + i * (i>=0), type(node_u), None, None, None])
        elif type(node_u) == ast.For:
            if type(node_u.target) == ast.Tuple:
                for elt in node_u.target.elts:
                    #return_name_table.append(elt.id)
                    return_name_table.append([elt.id, j * (i<0) + i * (i>=0), type(node_u), None, None, None])
            elif type(node_u.target) == ast.Name:
                #return_name_table.append(node_u.target.id)
                return_name_table.append([node_u.target.id, j * (i<0) + i * (i>=0), type(node_u), None, None, None])

            return_name_table = return_name_table + body_dig(node_u, j * (i<0) + i * (i>=0))
        
        elif type(node_u) == ast.FunctionDef:
            return_name_table.append([node_u.name, j * (i<0) + i * (i>=0), type(node_u), None, None, None])
        elif type(node_u) == ast.While:
            return_name_table = return_name_table + body_dig(node_u, j * (i<0) + i * (i>=0))
        elif type(node_u) == ast.If:
            return_name_table = return_name_table + body_dig(node_u, j * (i<0) + i * (i>=0))
    return return_name_table

In [10]:
#@advance
def name_info_df(func_p):
    func_name_table = body_dig(func_p)
    if func_name_table == []:
        return_name_df = pd.DataFrame(
            columns=['name', 'idx', 'type', 'module', 'import', 'as']
        )
    else:
        return_name_df = pd.DataFrame(
            data=np.array(func_name_table),
            columns=['name', 'idx', 'type', 'module', 'import', 'as']
        )
    return return_name_df

In [11]:
add_name_df = name_info_df(add_p)
base_name_df = name_info_df(base_p)

In [12]:
#@ignore
display(base_name_df)

,name,idx,type,module,import,as
0,nbtof_test_b,0,<class 'ast.For'>,None,None,None
1,nbtof_test_c,0,<class 'ast.Assign'>,None,None,None
2,i,0,<class 'ast.For'>,None,None,None
3,nbtof_test_d,0,<class 'ast.Assign'>,None,None,None
4,i,1,<class 'ast.For'>,None,None,None
5,j,1,<class 'ast.For'>,None,None,None
6,nbtof_test_c,1,<class 'ast.Assign'>,None,None,None
7,instnat_num,2,<class 'ast.Assign'>,None,None,None
8,kk,3,<class 'ast.Assign'>,None,None,None
9,instnat_num,3,<class 'ast.Assign'>,None,None,None
10,concat_dum,4,<class 'ast.FunctionDef'>,None,None,None
11,plt,5,<class 'ast.Import'>,None,matplotlib.pyplot,plt
12,np,6,<class 'ast.Import'>,None,numpy,np
13,pd,6,<class 'ast.Import'>,None,pandas,pd
14,random,6,<class 'ast.Import'>,None,random,None
15,plt,7,<class 'ast.ImportFrom'>,matplotlib,pyplot,plt
16,curve_fit,8,<class 'ast.ImportFrom'>,scipy.optimize,curve_fit,None
17,ConstantKernel,9,<class 'ast.ImportFrom'>,sklearn.gaussian_process.kernels,ConstantKernel,None
18,RBF,9,<class 'ast.ImportFrom'>,sklearn.gaussian_process.kernels,RBF,None
19,WhiteKernel,9,<class 'ast.ImportFrom'>,sklearn.gaussian_process.kernels,WhiteKernel,None
20,nbtof_test_a,10,<class 'ast.Assign'>,None,None,None
21,nbtof_test_b,10,<class 'ast.Assign'>,None,None,None
22,nbtof_test_c,11,<class 'ast.Assign'>,None,None,None
23,nbtof_test_d,11,<class 'ast.Assign'>,None,None,None
24,sample_a,12,<class 'ast.FunctionDef'>,None,None,None

In [13]:
#@ignore
for idx, node in enumerate(add_p.body):
    instant_name_df = add_name_df[add_name_df['idx'] == idx]
    display(type(node))
    display(instant_name_df)

ast.Import

     name idx                  type module  import    as
0      np   0  <class 'ast.Import'>   None   numpy    np
1      pd   0  <class 'ast.Import'>   None  pandas    pd
2  random   0  <class 'ast.Import'>   None  random  None

ast.Import

  name idx                  type module import    as
3  cv2   1  <class 'ast.Import'>   None    cv2  None

ast.Import

  name idx                  type module             import   as
4  plt   2  <class 'ast.Import'>   None  matplotlib.pyplot  plt

ast.ImportFrom

       name idx                      type             module    import    as
5  interp1d   3  <class 'ast.ImportFrom'>  scipy.interpolate  interp1d  None

ast.Assign

           name idx                  type module import    as
6  ast_sample_a   4  <class 'ast.Assign'>   None   None  None

ast.FunctionDef

         name idx                       type module import    as
7  concat_dum   5  <class 'ast.FunctionDef'>   None   None  None

ast.FunctionDef

       name idx                       type module import    as
8  sample_b   6  <class 'ast.FunctionDef'>   None   None  None

In [14]:
#@advance
def import_str(name_ds):
    if name_ds['module'] is not None:
        return name_ds['module'] + '.' + name_ds['import']
    else:
        return name_ds['import']

In [15]:
#@advance
def new_import_check(add_name_ds, base_name_df):
    #add_import_info_alist = add_name_df.iloc[4][['module', 'import', 'as']].values
    #base_import_info_array = base_name_df[['module', 'import', 'as']].values
    concat_status = 'new'
    for _, base_name_ds in base_name_df.iterrows():
        if (add_name_ds['name'] == base_name_ds['name'])*(import_str(add_name_ds) == import_str(base_name_ds)):
            concat_status = 'exist'
        elif (add_name_ds['name'] == base_name_ds['name'])*(import_str(add_name_ds) != import_str(base_name_ds)):
            concat_status = 'error'
    return concat_status

In [16]:
return_p = copy.deepcopy(base_p)
return_body_list = []
for idx, node in enumerate(add_p.body):
    instant_name_df = add_name_df[add_name_df['idx'] == idx]
    if (type(node) == ast.Import) + (type(node) == ast.ImportFrom):
        for _, instant_name_ds in instant_name_df.iterrows():
            concat_status = new_import_check(instant_name_ds, base_name_df)
            #print(instant_name_ds['name'], concat_status)
            if (concat_status == 'new')&(instant_name_ds['type'] == ast.Import):
                instant_module = ast.Import(
                    names=[
                        ast.alias(
                            name = instant_name_ds['import'], 
                            asname=instant_name_ds['as']
                            )
                        ]
                    )
                return_body_list.append(copy.deepcopy(instant_module))
            elif (concat_status == 'new')&(instant_name_ds['type'] == ast.ImportFrom):
                instant_module = ast.ImportFrom(
                    module=instant_name_ds['module'],
                    names=[
                        ast.alias(
                            name = instant_name_ds['import'], 
                            asname=instant_name_ds['as']
                            )
                        ],
                    level=0
                    )
                return_body_list.append(copy.deepcopy(instant_module))
    elif (type(node) == ast.FunctionDef):
        add_func_name = add_name_df[(add_name_df['idx'] == idx)&(add_name_df['type'] == ast.FunctionDef)]['name'].values[0]
        return_body_list.append(copy.deepcopy(node))
        for _, instant_name_ds in base_name_df.iterrows():
            if (instant_name_ds['name'] == add_func_name)&(instant_name_ds['type'] == ast.FunctionDef):
                return_p.body[instant_name_ds['idx']] = copy.deepcopy(node)
                return_body_list = return_body_list[:-1]        
                break
    else:
        return_body_list.append(copy.deepcopy(node))
        
return_p.body = return_p.body + return_body_list

In [17]:
if auto_sort:
    auto_sort_table = [
        [ast.Import], 
        [ast.ImportFrom],
        [ast.Assign, ast.AnnAssign, ast.For, ast.AsyncFor, ast.While, ast.Raise, ast.If, ast.ClassDef, ast.With, ast.Expr],
        [ast.FunctionDef, ast.AsyncFunctionDef],
        [ast.Delete, ast.Return, ast.Break, ast.Continue, ast.Pass],
        ]
    sort_body_list = []
    for auto_sort_list in auto_sort_table:
        for node in return_p.body:
            if type(node) in auto_sort_list:
                sort_body_list.append(copy.deepcopy(node))
    return_p.body = sort_body_list

In [18]:
#@ignore
display(return_p.body)

[<ast.Import at 0x1c8458d83d0>,
 <ast.Import at 0x1c8458d83a0>,
 <ast.Import at 0x1c8458d82e0>,
 <ast.ImportFrom at 0x1c8458da110>,
 <ast.ImportFrom at 0x1c8458d9ba0>,
 <ast.ImportFrom at 0x1c8458d8220>,
 <ast.ImportFrom at 0x1c8458d81f0>,
 <ast.For at 0x1c8458d8100>,
 <ast.For at 0x1c8458db8e0>,
 <ast.Assign at 0x1c8458d8280>,
 <ast.While at 0x1c8458daaa0>,
 <ast.Assign at 0x1c8458d80d0>,
 <ast.Assign at 0x1c8458da170>,
 <ast.Assign at 0x1c8458d8580>,
 <ast.FunctionDef at 0x1c8458d9cf0>,
 <ast.FunctionDef at 0x1c8458db9d0>,
 <ast.FunctionDef at 0x1c8458dbcd0>]

In [19]:
#@ignore
output_str = ''
indent_num = 0
for c in ast.dump(return_p):
    if c == '(':
        indent_num = indent_num + 1
        output_str = output_str + c
        output_str = output_str + '\n' + '  '*indent_num
    elif c == ')':
        indent_num = indent_num - 1
        output_str = output_str + c
    elif c == '[':
        indent_num = indent_num + 1
        output_str = output_str + c
        output_str = output_str + '\n' + '  '*indent_num
    elif c == ']':
        indent_num = indent_num - 1
        output_str = output_str + c
    elif c == ',':
        output_str = output_str + c + '\n' + '  '*indent_num
    elif c == ' ':
        pass
    else:
        output_str = output_str + c
print(output_str)

Module(
  body=[
    Import(
      names=[
        alias(
          name='matplotlib.pyplot',
          asname='plt')]),
    Import(
      names=[
        alias(
          name='numpy',
          asname='np'),
        alias(
          name='pandas',
          asname='pd'),
        alias(
          name='random')]),
    Import(
      names=[
        alias(
          name='cv2')]),
    ImportFrom(
      module='matplotlib',
      names=[
        alias(
          name='pyplot',
          asname='plt')],
      level=0),
    ImportFrom(
      module='scipy.optimize',
      names=[
        alias(
          name='curve_fit')],
      level=0),
    ImportFrom(
      module='sklearn.gaussian_process.kernels',
      names=[
        alias(
          name='ConstantKernel'),
        alias(
          name='RBF'),
        alias(
          name='WhiteKernel')],
      level=0),
    ImportFrom(
      module='scipy.interpolate',
      names=[
        alias(
          name='interp1d')],
      level=0),
    For(
      target=Name(
        id='nbtof_test_b',
        ctx=Store(
          )),
      iter=Call(
        func=Name(
          id='range',
          ctx=Load(
            )),
        args=[
          Constant(
            value=1),
          Constant(
            value=10)],
        keywords=[
          ]),
      body=[
        Assign(
          targets=[
            Name(
              id='nbtof_test_c',
              ctx=Store(
                ))],
          value=Constant(
            value=4)),
        For(
          target=Name(
            id='i',
            ctx=Store(
              )),
          iter=Call(
            func=Name(
              id='range',
              ctx=Load(
                )),
            args=[
              Constant(
                value=4),
              Constant(
                value=6)],
            keywords=[
              ]),
          body=[
            Assign(
              targets=[
                Name(
                  id='nbtof_test_d',
                  ctx=Store(
                    ))],
              value=Name(
                id='i',
                ctx=Load(
                  ))),
            Expr(
              value=Call(
                func=Name(
                  id='print',
                  ctx=Load(
                    )),
                args=[
                  Name(
                    id='nbtof_test_d',
                    ctx=Load(
                      )),
                  Name(
                    id='nbtof_test_c',
                    ctx=Load(
                      ))],
                keywords=[
                  ]))],
          orelse=[
            ])],
      orelse=[
        ]),
    For(
      target=Tuple(
        elts=[
          Name(
            id='i',
            ctx=Store(
              )),
          Name(
            id='j',
            ctx=Store(
              ))],
        ctx=Store(
          )),
      iter=Call(
        func=Name(
          id='enumerate',
          ctx=Load(
            )),
        args=[
          Call(
            func=Name(
              id='range',
              ctx=Load(
                )),
            args=[
              Constant(
                value=1),
              Constant(
                value=10)],
            keywords=[
              ])],
        keywords=[
          ]),
      body=[
        Assign(
          targets=[
            Name(
              id='nbtof_test_c',
              ctx=Store(
                ))],
          value=Constant(
            value=4))],
      orelse=[
        ]),
    Assign(
      targets=[
        Name(
          id='instnat_num',
          ctx=Store(
            ))],
      value=Constant(
        value=1)),
    While(
      test=Constant(
        value=True),
      body=[
        If(
          test=Compare(
            left=Name(
              id='instnat_num',
              ctx=Load(
                )),
            ops=[
              Gt(
                )],
            comparators=[
              Constant(
                value=5)]),
          body=[
            Assign(
              targets=[
                Name(
                  id='kk',
                  ctx=Store(
                    ))],
              value=Constant(
                value=3)),
            Break(
              )],
          orelse=[
            ]),
        Assign(
          targets=[
            Name(
              id='instnat_num',
              ctx=Store(
                ))],
          value=BinOp(
            left=Name(
              id='instnat_num',
              ctx=Load(
                )),
            op=Add(
              ),
            right=Constant(
              value=1)))],
      orelse=[
        ]),
    Assign(
      targets=[
        Tuple(
          elts=[
            Name(
              id='nbtof_test_a',
              ctx=Store(
                )),
            Name(
              id='nbtof_test_b',
              ctx=Store(
                ))],
          ctx=Store(
            ))],
      value=Tuple(
        elts=[
          Constant(
            value=1),
          Constant(
            value=2)],
        ctx=Load(
          ))),
    Assign(
      targets=[
        Tuple(
          elts=[
            Name(
              id='nbtof_test_c',
              ctx=Store(
                )),
            Name(
              id='nbtof_test_d',
              ctx=Store(
                ))],
          ctx=Store(
            ))],
      value=Tuple(
        elts=[
          Constant(
            value=3),
          Constant(
            value=4)],
        ctx=Load(
          ))),
    Assign(
      targets=[
        Name(
          id='ast_sample_a',
          ctx=Store(
            ))],
      value=Constant(
        value=1)),
    FunctionDef(
      name='concat_dum',
      args=arguments(
        posonlyargs=[
          ],
        args=[
          ],
        kwonlyargs=[
          ],
        kw_defaults=[
          ],
        defaults=[
          ]),
      body=[
        Expr(
          value=Call(
            func=Name(
              id='print',
              ctx=Load(
                )),
            args=[
              Constant(
                value='sample_b')],
            keywords=[
              ])),
        Return(
          value=Constant(
            value=None))],
      decorator_list=[
        ]),
    FunctionDef(
      name='sample_a',
      args=arguments(
        posonlyargs=[
          ],
        args=[
          arg(
            arg='x'),
          arg(
            arg='y')],
        vararg=arg(
          arg='params'),
        kwonlyargs=[
          arg(
            arg='deg_for_fit')],
        kw_defaults=[
          Constant(
            value=4)],
        kwarg=arg(
          arg='kwargs'),
        defaults=[
          ]),
      body=[
        Expr(
          value=Constant(
            value='\nfdhjafsl\n')),
        FunctionDef(
          name='fit_func',
          args=arguments(
            posonlyargs=[
              ],
            args=[
              arg(
                arg='get_x')],
            vararg=arg(
              arg='params'),
            kwonlyargs=[
              ],
            kw_defaults=[
              ],
            defaults=[
              ]),
          body=[
            Assign(
              targets=[
                Name(
                  id='return_y',
                  ctx=Store(
                    ))],
              value=Call(
                func=Attribute(
                  value=Name(
                    id='np',
                    ctx=Load(
                      )),
                  attr='zeros_like',
                  ctx=Load(
                    )),
                args=[
                  Name(
                    id='get_x',
                    ctx=Load(
                      ))],
                keywords=[
                  ])),
            For(
              target=Tuple(
                elts=[
                  Name(
                    id='i',
                    ctx=Store(
                      )),
                  Name(
                    id='param',
                    ctx=Store(
                      ))],
                ctx=Store(
                  )),
              iter=Call(
                func=Name(
                  id='enumerate',
                  ctx=Load(
                    )),
                args=[
                  Name(
                    id='params',
                    ctx=Load(
                      ))],
                keywords=[
                  ]),
              body=[
                Assign(
                  targets=[
                    Name(
                      id='return_y',
                      ctx=Store(
                        ))],
                  value=BinOp(
                    left=Name(
                      id='return_y',
                      ctx=Load(
                        )),
                    op=Add(
                      ),
                    right=Call(
                      func=Attribute(
                        value=Name(
                          id='np',
                          ctx=Load(
                            )),
                        attr='array',
                        ctx=Load(
                          )),
                      args=[
                        BinOp(
                          left=Name(
                            id='param',
                            ctx=Load(
                              )),
                          op=Mult(
                            ),
                          right=BinOp(
                            left=Name(
                              id='get_x',
                              ctx=Load(
                                )),
                            op=Pow(
                              ),
                            right=Name(
                              id='i',
                              ctx=Load(
                                ))))],
                      keywords=[
                        ])))],
              orelse=[
                ]),
            Return(
              value=Name(
                id='return_y',
                ctx=Load(
                  )))],
          decorator_list=[
            ]),
        Assign(
          targets=[
            Tuple(
              elts=[
                Name(
                  id='popt',
                  ctx=Store(
                    )),
                Name(
                  id='pcov',
                  ctx=Store(
                    ))],
              ctx=Store(
                ))],
          value=Call(
            func=Name(
              id='curve_fit',
              ctx=Load(
                )),
            args=[
              Name(
                id='fit_func',
                ctx=Load(
                  )),
              Name(
                id='x',
                ctx=Load(
                  )),
              Name(
                id='y',
                ctx=Load(
                  ))],
            keywords=[
              keyword(
                arg='p0',
                value=Call(
                  func=Name(
                    id='list',
                    ctx=Load(
                      )),
                  args=[
                    Call(
                      func=Attribute(
                        value=Name(
                          id='np',
                          ctx=Load(
                            )),
                        attr='ones',
                        ctx=Load(
                          )),
                      args=[
                        BinOp(
                          left=Name(
                            id='deg_for_fit',
                            ctx=Load(
                              )),
                          op=Add(
                            ),
                          right=Constant(
                            value=1))],
                      keywords=[
                        ])],
                  keywords=[
                    ]))])),
        Assign(
          targets=[
            Name(
              id='check_y',
              ctx=Store(
                ))],
          value=Call(
            func=Name(
              id='fit_func',
              ctx=Load(
                )),
            args=[
              Name(
                id='x',
                ctx=Load(
                  )),
              Starred(
                value=Name(
                  id='popt',
                  ctx=Load(
                    )),
                ctx=Load(
                  ))],
            keywords=[
              ])),
        Return(
          value=Name(
            id='check_y',
            ctx=Load(
              )))],
      decorator_list=[
        ]),
    FunctionDef(
      name='sample_b',
      args=arguments(
        posonlyargs=[
          ],
        args=[
          arg(
            arg='a'),
          arg(
            arg='b')],
        vararg=arg(
          arg='args'),
        kwonlyargs=[
          ],
        kw_defaults=[
          ],
        defaults=[
          ]),
      body=[
        Assign(
          targets=[
            Name(
              id='numpy',
              ctx=Store(
                ))],
          value=Constant(
            value=1)),
        Assign(
          targets=[
            Name(
              id='return_num',
              ctx=Store(
                ))],
          value=Constant(
            value=0)),
        For(
          target=Name(
            id='arg',
            ctx=Store(
              )),
          iter=Name(
            id='args',
            ctx=Load(
              )),
          body=[
            Assign(
              targets=[
                Name(
                  id='return_num',
                  ctx=Store(
                    ))],
              value=BinOp(
                left=Name(
                  id='return_num',
                  ctx=Load(
                    )),
                op=Add(
                  ),
                right=Name(
                  id='arg',
                  ctx=Load(
                    ))))],
          orelse=[
            ]),
        Assign(
          targets=[
            Name(
              id='return_num',
              ctx=Store(
                ))],
          value=BinOp(
            left=BinOp(
              left=Name(
                id='return_num',
                ctx=Load(
                  )),
              op=Add(
                ),
              right=Name(
                id='a',
                ctx=Load(
                  ))),
            op=Add(
              ),
            right=Name(
              id='b',
              ctx=Load(
                )))),
        Return(
          value=Name(
            id='return_num',
            ctx=Load(
              )))],
      decorator_list=[
        ])],
  type_ignores=[
    ])

In [20]:
with open(base_py_file_name, mode='w') as f:
    f.write(ast.unparse(return_p))

In [21]:
#@return
True

True

In [22]:
#@ignore
import nbtof_base
nbtof_base.nbtof_base(__vsc_ipynb_file__, func_name='nbtof_update_base')

('c:\\Users\\1618s\\OneDrive\\Programs\\04_tool\\function_maker\\nbtof_concat.py',
 None)